# ==================================================================================
#
#       Copyright (c) 2025 Kyunghee University, Mobile Communication Lab. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# ==================================================================================

# For reading secrets in Kubeflow-Pipeline and SDK

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret_reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret_pipeline_runner_rb
  namespace: traininghost
subjects:
- kind: ServiceAccount
  name: pipeline-runner
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: secret_reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traininghost_default_secret_rb
  namespace: kubeflow
subjects:
- kind: ServiceAccount
  name: default
  namespace: traininghost
roleRef:
  kind: ClusterRole
  name: secret_reader
  apiGroup: rbac.authorization.k8s.io