AIMLTrainingservice:
  AefProfiles:
  - interfaceDescriptions:
    - ipv4Addr: <IP ADDRESS FOR Training Manager>
      port: 32002
      securityMethods:
      - PSK
    Versions:
      - ApiVersion: ""
        Resources:
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - POST
          ResourceName: "FeatureGroup"
          Uri: "ai-ml-model-training/v1/featureGroup"
        - CommType: REQUEST_RESPONSE
          Operations:
          - POST
          - GET
          ResourceName: "CreateTrainingJob"
          Uri: "ai-ml-model-training/v1/training-jobs"
        - CommType: REQUEST_RESPONSE
          Operations:
          - POST
          ResourceName: "StartTraining"
          Uri: "ai-ml-model-training/v1/training-jobs/{training_job_id}/training"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "GetTrainingJob"
          Uri: "ai-ml-model-training/v1/training-jobs/{training_job_id}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - DELETE
          ResourceName: "DeleteTrainingJob"
          Uri: "ai-ml-model-training/v1/training-jobs/{training_job_id}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "GetTrainingJobStatus"
          Uri: "ai-ml-model-training/v1/training-jobs/{training_job_id}/status"      
  ApiName: AIMLT-TM-requests


