AIMLTrainingservice:
  AefProfiles:
  - interfaceDescriptions:
    - ipv4Addr: <IP ADDRESS FOR Training Manager>
      port: 32002
      securityMethods:
      - PSK
    Versions:
      - ApiVersion: ""
        Resources:
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getPipeline"
          Uri: "/pipelines"
        - CommType: REQUEST_RESPONSE
          Operations:
          - POST
          ResourceName: "CreateFeatureGroup"
          Uri: "/featureGroup"
        - CommType: REQUEST_RESPONSE
          Operations:
          - POST
          ResourceName: "CreateTrainingJob"
          Uri: "/trainingjobs/{training_job_id}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - POST
          ResourceName: "StartTraining"
          Uri: "/trainingjobs/{training_job_id}/training"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "GetTrainingJob"
          Uri: "/trainingjobs/{training_job_id}/{version}"
  ApiName: AIMLT-http10


