apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
spec:
  template:
    metadata:
      labels:
        app: ml-pipeline-ui
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: ml-pipeline-ui-configmap
      containers:
        - name: ml-pipeline-ui
          env:
            - name: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
